"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService();
var result;
var p = new Product_1.Product();
p.name = "Iphone 13";
p.price = 4000;
p.category = "Telefon";
p.id = 5;
_productService.saveProduct(p);
//result = _productService.getProducts();
result = _productService.getById(5);
result = _productService.getProducts();
console.log(result);
